name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: Install apt dependencies
        run: |
          which swig
          sudo apt-get install \
            swig3.0 libatlas-base-dev libhdf5-serial-dev
          #sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
      - name: Install pip dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          bash Test/run_tests.sh

