name: Tests

on: [pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-ci

      - name: Install apt dependencies
        run: |
          sudo apt-get install \
            swig3.0 libatlas-base-dev libhdf5-serial-dev
      
      - name: Download COPASI
        run: |
          COPASI_VERSION="4.29.228-Linux-64bit"
          wget "https://github.com/copasi/COPASI/releases/download/Build-228/COPASI-${COPASI_VERSION}.tar.gz"
          tar -xzvf COPASI-${COPASI_VERSION}.tar.gz
          mv COPASI-${COPASI_VERSION} COPASI
          export DIR_COPASI_BIN=`pwd`/COPASI/bin

      - name: Install pip dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        timeout-minutes: 60
        run: |
          bash Test/run_tests.sh
