name: Tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install apt dependencies
        run: |
          which conda
      - name: Run tests
        run: |
          bash Test/run_tests.sh

